{% set name = "darr" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf2e608bbcf7bfc7835a1066e5e8fed8394abd2be50dad3e6e40d8d171e40c00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.12
    - packaging >=20.0

test:
  imports:
    - darr

about:
  home: https://github.com/gbeckers/darr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >-
    A Python science library that stores NumPy arrays in a way that is self-documented and tool-independent.
  description: |
    Darr is a Python science library for disk-based NumPy arrays that
    persist in a format that is simple, self-documented and tool-independent.
    It enables you to work efficiently with potentially very large arrays, while
    keeping your data easily accessible from a wide range of computing
    environments. Even if you don't work with very large arrays, Darr is a 
    convenient way to store your arrays in a way that keeps them universally
    readable and documented, which is in line with good scientific practice. 
    Auto-documentation includes code for reading the array in a variety of 
    current scientific data tools such as Python, R, Julia, IDL, Matlab, Maple, 
    and Mathematica. It is trivially easy to share your data with others or 
    with yourself when working in different computing environments, no 
    exporting or much explanation required.
  doc_url: https://darr.readthedocs.io/
  dev_url: https://github.com/gbeckers/darr

extra:
  recipe-maintainers:
    - gbeckers
