{% set name = "darr" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4230a1051992e4e2f3b1043e482413df4afd11c32dc12fe67ac25937669f5ccf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.12

test:
  imports:
    - darr

about:
  home: https://github.com/gbeckers/darr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >-
    A Python science library for memory-mapped numeric arrays, based on a format
    that is self-explanatory and tool-independent.
  description: |
    Darr is a Python science library for disk-based NumPy arrays that persist in
    a format that is simple, self-documented and tool-independent. It enables
    you to work efficiently with potentially very large arrays, while keeping 
    your data easily accessible from a wide range of computing environments.  
    Self-documentation includes code for reading the array in a variety of 
    current scientific data tools such as Python, R, Julia, IDL, Matlab, 
    Maple, and Mathematica. It is trivially easy to share your data with 
    others or with yourself when working in different computing environments.
  doc_url: https://darr.readthedocs.io/
  dev_url: https://github.com/gbeckers/darr

extra:
  recipe-maintainers:
    - gbeckers
