{% set name = "darr" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fdcfbfb23d9b78cdbdc8eacaf53b2fbc80f4aa398c96fa279c4b2676fe25e6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.12

test:
  imports:
    - darr

about:
  home: https://github.com/gbeckers/darr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >-
    A Python science library for memory-mapped numeric arrays, based on a format that is self-explanatory and tool-independent.
  description: |
    Darr is a Python science library that enables you to work efficiently with
    disk-based numeric arrays without depending on tool-specific data formats.
    This makes it easy to share your data with those who do not use Darr or even
    Python. No exporting required and, as the data is saved in a self-explanatory
    way, not much explanation required either. Tool-independent and easy access
    to data is in line with good scientific practice as it promotes wide and
    long-term availability, to others but also to yourself.
  doc_url: https://darr.readthedocs.io/
  dev_url: https://github.com/gbeckers/darr

extra:
  recipe-maintainers:
    - gbeckers
