{% set name = "darr" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7755301f30a974860fd87f632f81ead1932f8c8cba577a28c8ee93de8e9e31f7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.12

test:
  imports:
    - darr

about:
  home: https://github.com/gbeckers/darr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >-
    A Python library for memory-mapped numeric arrays, based on a format
    that is self-explanatory and tool-independent.
  description: |
    Darr is a Python science library for working efficiently with potentially
    large, disk-based numeric arrays and metadata, without depending on
    tool-specific or complicated data formats. Data is persistent on disk in a
    self-explanatory way, making it trivially easy to share it and use it in
    different environments. No need to export anything or to provide much
    explanation, and no need to assume that a specific tool will be available.
    Tool-independent and easy access to data is in line with good scientific
    practice as it promotes wide and long-term availability, to others and
    to yourself.
  doc_url: https://darr.readthedocs.io/
  dev_url: https://github.com/gbeckers/darr

extra:
  recipe-maintainers:
    - gbeckers
